CREATE TABLE `tickets_fun` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `pid` varchar(128) DEFAULT NULL COMMENT '妙计产品ID',
  `sid` varchar(128) NOT NULL COMMENT '供应商ID/源ID',
  `name` varchar(128) NOT NULL COMMENT '票务名称',
  `info` text DEFAULT NULL COMMENT '票务信息',
  `ccy` varchar(128) NOT NULL COMMENT '币种',
  `price` float(11) NOT NULL COMMENT '价格',
  `times` text NOT NULL COMMENT '门票对应的场次的开始时间及持续时间',
  `date` varchar(128) NOT NULL COMMENT '门票适用的日期 精确到天和周',
  `book_pre` int(11) DEFAULT 0 COMMENT '前预定时间 单位秒 当日可定为0',
  `enter_pre` int(11) DEFAULT 0 COMMENT '提前入场时间 单位秒 默认为0',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `utime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `ticketType` int(11) NOT NULL COMMENT '票务类型 1:常规票券 2:套餐票券 3:自费项目',
  `max` int(4) DEFAULT -1 COMMENT '最多预订人数',
  `min` int(4) DEFAULT -1 COMMENT '最少预订人数',
  `agemin` int(3) DEFAULT -1 COMMENT '年龄起始',
  `agemax` int(3) DEFAULT -1 COMMENT '年龄终止',
  `ticket_3rd` text DEFAULT NULL COMMENT '第三方的票种ID',
  `traveller_3rd` text DEFAULT NULL COMMENT '第三方的游客规格ID',
  `id_3rd` int(5) NOT NULL COMMENT '第三方的索引',
  PRIMARY KEY (`id`),
  KEY `name`(`name`),
  KEY `id_3rd`(`id_3rd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩乐门票表';


CREATE TABLE `view_ticket` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `pid` varchar(128) DEFAULT NULL COMMENT '格式vt+id+ptid',
  `ptid` varchar(128) DEFAULT NULL COMMENT '合作方ID 私有数据才有',
  `poi_mode` int(11) NOT NULL COMMENT 'POI类型ID 参考全局通用字段poi mode',
  `ref_poi` varchar(128) DEFAULT 0 COMMENT '关联景点ID',
  `name` varchar(128) DEFAULT NULL COMMENT '票务名称',
  `ename` varchar(128) DEFAULT NULL COMMENT '英文名称',
  `city_id` varchar(128) NOT NULL COMMENT '城市ID',
  `first_img` varchar(1024) DEFAULT NULL COMMENT '首张图片',
  `img_list` text DEFAULT NULL COMMENT '图片列表',
  `times` text NOT NULL COMMENT '门票对应的场次的开始时间及持续时间',
  `date` varchar(128) NOT NULL COMMENT '门票适用的日期 精确到天和周',
  `book_pre` int(11) DEFAULT 0 COMMENT '前预定时间 单位秒 当日可定为0',
  `enter_pre` int(11) DEFAULT 0 COMMENT '提前入场时间 单位秒 默认为0',
  `jiesong_type` int(2) DEFAULT 0 COMMENT '0:不接送 1:指定地点接送(需要具体地点) 2:市内任意酒店',
  `jiesong_poi` text DEFAULT NULL COMMENT '格式:[{"addr":"地址","coord":"坐标"},{}]',
  `info` text DEFAULT NULL COMMENT '英文名称',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `utime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `ticket_3rd` text DEFAULT NULL COMMENT '第三方的产品ID',
  `tag` text DEFAULT NULL COMMENT '产品标签, 用|分割',
  `id_3rd` int(5) NOT NULL COMMENT '第三方的索引',
  PRIMARY KEY (`id`),
  KEY `name`(`name`),
  KEY `id_3rd`(`id_3rd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='景点门票';


CREATE TABLE `play_ticket` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `pid` varchar(128) DEFAULT NULL COMMENT '玩乐活动ID 格式pt+id+ptid',
  `ptid` varchar(128) DEFAULT NULL COMMENT '合作方ID',
  `poi_mode` int(11) NOT NULL COMMENT 'POI类型ID 参考全局通用字段poi mode',
  `ref_poi` varchar(128) DEFAULT 0 COMMENT '关联景点ID',
  `name` varchar(128) DEFAULT NULL COMMENT '票务名称',
  `ename` varchar(128) DEFAULT NULL COMMENT '英文名称',
  `city_id` varchar(128) NOT NULL COMMENT '城市ID',
  `addr` varchar(256) NOT NULL COMMENT '活动地址',
  `map_info` varchar(256) NOT NULL COMMENT '活动地址的坐标',
  `first_img` varchar(1024) DEFAULT NULL COMMENT '首张图片',
  `img_list` text DEFAULT NULL COMMENT '图片列表',
  `times` text NOT NULL COMMENT '门票对应的场次的开始时间及持续时间',
  `date` varchar(128) NOT NULL COMMENT '门票适用的日期 精确到天和周',
  `book_pre` int(11) DEFAULT 0 COMMENT '前预定时间 单位秒 当日可定为0',
  `enter_pre` int(11) DEFAULT 0 COMMENT '提前入场时间 单位秒 默认为0',
  `jiesong_type` int(2) DEFAULT 0 COMMENT '0:不接送 1:指定地点接送(需要具体地点) 2:市内任意酒店',
  `jiesong_poi` text DEFAULT NULL COMMENT '格式:[{"addr":"地址","coord":"坐标"},{}]',
  `info` text DEFAULT NULL COMMENT '英文名称',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `utime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `ticket_3rd` text DEFAULT NULL COMMENT '第三方的产品ID',
  `tag` text DEFAULT NULL COMMENT '产品标签, 用|分割',
  `id_3rd` int(5) NOT NULL COMMENT '第三方的索引',
  PRIMARY KEY (`id`),
  KEY `name`(`name`),
  KEY `id_3rd`(`id_3rd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='演出赛事';


CREATE TABLE `activity_ticket` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `pid` varchar(128) DEFAULT NULL COMMENT '玩乐活动ID 格式pt+id+ptid',
  `ptid` varchar(128) DEFAULT NULL COMMENT '合作方ID',
  `poi_mode` int(11) NOT NULL COMMENT 'POI类型ID 参考全局通用字段poi mode',
  `ref_poi` varchar(128) DEFAULT 0 COMMENT '关联景点ID',
  `name` varchar(128) DEFAULT NULL COMMENT '票务名称',
  `ename` varchar(128) DEFAULT NULL COMMENT '英文名称',
  `city_id` varchar(128) NOT NULL COMMENT '城市ID',
  `addr` varchar(256) NOT NULL COMMENT '活动地址',
  `map_info` varchar(256) NOT NULL COMMENT '活动地址的坐标',
  `first_img` varchar(1024) DEFAULT NULL COMMENT '首张图片',
  `img_list` text DEFAULT NULL COMMENT '图片列表',
  `times` text NOT NULL COMMENT '门票对应的场次的开始时间及持续时间',
  `date` varchar(128) NOT NULL COMMENT '门票适用的日期 精确到天和周',
  `book_pre` int(11) DEFAULT 0 COMMENT '前预定时间 单位秒 当日可定为0',
  `enter_pre` int(11) DEFAULT 0 COMMENT '提前入场时间 单位秒 默认为0',
  `jiesong_type` int(2) DEFAULT 0 COMMENT '0:不接送 1:指定地点接送(需要具体地点) 2:市内任意酒店',
  `jiesong_poi` text DEFAULT NULL COMMENT '格式:[{"addr":"地址","coord":"坐标"},{}]',
  `info` text DEFAULT NULL COMMENT '英文名称',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `utime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `ticket_3rd` text DEFAULT NULL COMMENT '第三方的产品ID',
  `tag` text DEFAULT NULL COMMENT '产品标签, 用|分割',
  `id_3rd` int(5) NOT NULL COMMENT '第三方的索引',
  PRIMARY KEY (`id`),
  KEY `name`(`name`),
  KEY `id_3rd`(`id_3rd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特色活动';

CREATE TABLE `tour_ticket` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `pid` varchar(128) DEFAULT NULL COMMENT '玩乐活动ID 格式pt+id+ptid',
  `ptid` varchar(128) DEFAULT NULL COMMENT '合作方ID',
  `poi_mode` int(11) NOT NULL COMMENT 'POI类型ID 参考全局通用字段poi mode',
  `ref_poi` varchar(128) DEFAULT 0 COMMENT '关联景点ID',
  `name` varchar(128) DEFAULT NULL COMMENT '票务名称',
  `ename` varchar(128) DEFAULT NULL COMMENT '英文名称',
  `city_id` varchar(128) NOT NULL COMMENT '城市ID',
  `addr` varchar(256) NOT NULL COMMENT '活动地址',
  `map_info` varchar(256) NOT NULL COMMENT '活动地址的坐标',
  `first_img` varchar(1024) DEFAULT NULL COMMENT '首张图片',
  `img_list` text DEFAULT NULL COMMENT '图片列表',
  `times` text NOT NULL COMMENT '门票对应的场次的开始时间及持续时间',
  `date` varchar(128) NOT NULL COMMENT '门票适用的日期 精确到天和周',
  `book_pre` int(11) DEFAULT 0 COMMENT '前预定时间 单位秒 当日可定为0',
  `enter_pre` int(11) DEFAULT 0 COMMENT '提前入场时间 单位秒 默认为0',
  `jiesong_type` int(2) DEFAULT 0 COMMENT '0:不接送 1:指定地点接送(需要具体地点) 2:市内任意酒店',
  `jiesong_poi` text DEFAULT NULL COMMENT '格式:[{"addr":"地址","coord":"坐标"},{}]',
  `info` text DEFAULT NULL COMMENT '英文名称',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `utime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  `ticket_3rd` text DEFAULT NULL COMMENT '第三方的产品ID',
  `tag` text DEFAULT NULL COMMENT '产品标签, 用|分割',
  `id_3rd` int(5) NOT NULL COMMENT '第三方的索引',
  PRIMARY KEY (`id`),
  KEY `name`(`name`),
  KEY `id_3rd`(`id_3rd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='半日游/一日游/多日游';
