# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distance_protocol.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='distance_protocol.proto',
    package='Mioji.Distance',
    syntax='proto2',
    serialized_pb=_b(
        '\n\x17\x64istance_protocol.proto\x12\x0eMioji.Distance\"\xa1\x01\n\x17\x44istance_Single_Message\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x66\x61st\x18\x02 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x03 \x01(\x05\x12\x0c\n\x04walk\x18\x04 \x01(\x05\x12\x0c\n\x04time\x18\x05 \x01(\x05\x12\r\n\x05price\x18\x06 \x01(\x05\x12\x0e\n\x06source\x18\x07 \x01(\x05\x12\r\n\x05order\x18\x08 \x01(\x05\x12\x12\n\ntrans_type\x18\t \x01(\x05\"X\n\x10\x44istance_Message\x12\x44\n\x13\x64istance_single_vec\x18\x01 \x03(\x0b\x32\'.Mioji.Distance.Distance_Single_Message\"F\n\x1c\x44istance_Coor_Single_Message\x12\x0b\n\x03lng\x18\x01 \x01(\x02\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0c\n\x04\x66lag\x18\x03 \x01(\x05\"g\n\x15\x44istance_Coor_Message\x12N\n\x18\x64istance_coor_single_vec\x18\x01 \x03(\x0b\x32,.Mioji.Distance.Distance_Coor_Single_Message\"3\n\x15\x44istance_Info_Message\x12\x1a\n\x12\x62rief_introduction\x18\x01 \x01(\t\"\xe4\x01\n\x10Transfer_Message\x12\x44\n\x13\x64istance_single_vec\x18\x01 \x03(\x0b\x32\'.Mioji.Distance.Distance_Single_Message\x12\x44\n\x15\x64istance_coor_message\x18\x02 \x03(\x0b\x32%.Mioji.Distance.Distance_Coor_Message\x12\x44\n\x15\x64istance_info_message\x18\x03 \x03(\x0b\x32%.Mioji.Distance.Distance_Info_MessageB\x02H\x01')
)

_DISTANCE_SINGLE_MESSAGE = _descriptor.Descriptor(
    name='Distance_Single_Message',
    full_name='Mioji.Distance.Distance_Single_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='Mioji.Distance.Distance_Single_Message.type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='fast', full_name='Mioji.Distance.Distance_Single_Message.fast', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='dist', full_name='Mioji.Distance.Distance_Single_Message.dist', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='walk', full_name='Mioji.Distance.Distance_Single_Message.walk', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='time', full_name='Mioji.Distance.Distance_Single_Message.time', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='price', full_name='Mioji.Distance.Distance_Single_Message.price', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='source', full_name='Mioji.Distance.Distance_Single_Message.source', index=6,
            number=7, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='order', full_name='Mioji.Distance.Distance_Single_Message.order', index=7,
            number=8, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='trans_type', full_name='Mioji.Distance.Distance_Single_Message.trans_type', index=8,
            number=9, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=44,
    serialized_end=205,
)

_DISTANCE_MESSAGE = _descriptor.Descriptor(
    name='Distance_Message',
    full_name='Mioji.Distance.Distance_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='distance_single_vec', full_name='Mioji.Distance.Distance_Message.distance_single_vec', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=207,
    serialized_end=295,
)

_DISTANCE_COOR_SINGLE_MESSAGE = _descriptor.Descriptor(
    name='Distance_Coor_Single_Message',
    full_name='Mioji.Distance.Distance_Coor_Single_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='lng', full_name='Mioji.Distance.Distance_Coor_Single_Message.lng', index=0,
            number=1, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='lat', full_name='Mioji.Distance.Distance_Coor_Single_Message.lat', index=1,
            number=2, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='flag', full_name='Mioji.Distance.Distance_Coor_Single_Message.flag', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=297,
    serialized_end=367,
)

_DISTANCE_COOR_MESSAGE = _descriptor.Descriptor(
    name='Distance_Coor_Message',
    full_name='Mioji.Distance.Distance_Coor_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='distance_coor_single_vec', full_name='Mioji.Distance.Distance_Coor_Message.distance_coor_single_vec',
            index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=369,
    serialized_end=472,
)

_DISTANCE_INFO_MESSAGE = _descriptor.Descriptor(
    name='Distance_Info_Message',
    full_name='Mioji.Distance.Distance_Info_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='brief_introduction', full_name='Mioji.Distance.Distance_Info_Message.brief_introduction', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=474,
    serialized_end=525,
)

_TRANSFER_MESSAGE = _descriptor.Descriptor(
    name='Transfer_Message',
    full_name='Mioji.Distance.Transfer_Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='distance_single_vec', full_name='Mioji.Distance.Transfer_Message.distance_single_vec', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='distance_coor_message', full_name='Mioji.Distance.Transfer_Message.distance_coor_message', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='distance_info_message', full_name='Mioji.Distance.Transfer_Message.distance_info_message', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=528,
    serialized_end=756,
)

_DISTANCE_MESSAGE.fields_by_name['distance_single_vec'].message_type = _DISTANCE_SINGLE_MESSAGE
_DISTANCE_COOR_MESSAGE.fields_by_name['distance_coor_single_vec'].message_type = _DISTANCE_COOR_SINGLE_MESSAGE
_TRANSFER_MESSAGE.fields_by_name['distance_single_vec'].message_type = _DISTANCE_SINGLE_MESSAGE
_TRANSFER_MESSAGE.fields_by_name['distance_coor_message'].message_type = _DISTANCE_COOR_MESSAGE
_TRANSFER_MESSAGE.fields_by_name['distance_info_message'].message_type = _DISTANCE_INFO_MESSAGE
DESCRIPTOR.message_types_by_name['Distance_Single_Message'] = _DISTANCE_SINGLE_MESSAGE
DESCRIPTOR.message_types_by_name['Distance_Message'] = _DISTANCE_MESSAGE
DESCRIPTOR.message_types_by_name['Distance_Coor_Single_Message'] = _DISTANCE_COOR_SINGLE_MESSAGE
DESCRIPTOR.message_types_by_name['Distance_Coor_Message'] = _DISTANCE_COOR_MESSAGE
DESCRIPTOR.message_types_by_name['Distance_Info_Message'] = _DISTANCE_INFO_MESSAGE
DESCRIPTOR.message_types_by_name['Transfer_Message'] = _TRANSFER_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Distance_Single_Message = _reflection.GeneratedProtocolMessageType('Distance_Single_Message', (_message.Message,), dict(
    DESCRIPTOR=_DISTANCE_SINGLE_MESSAGE,
    __module__='distance_protocol_pb2'
    # @@protoc_insertion_point(class_scope:Mioji.Distance.Distance_Single_Message)
))
_sym_db.RegisterMessage(Distance_Single_Message)

Distance_Message = _reflection.GeneratedProtocolMessageType('Distance_Message', (_message.Message,), dict(
    DESCRIPTOR=_DISTANCE_MESSAGE,
    __module__='distance_protocol_pb2'
    # @@protoc_insertion_point(class_scope:Mioji.Distance.Distance_Message)
))
_sym_db.RegisterMessage(Distance_Message)

Distance_Coor_Single_Message = _reflection.GeneratedProtocolMessageType('Distance_Coor_Single_Message',
                                                                        (_message.Message,), dict(
        DESCRIPTOR=_DISTANCE_COOR_SINGLE_MESSAGE,
        __module__='distance_protocol_pb2'
        # @@protoc_insertion_point(class_scope:Mioji.Distance.Distance_Coor_Single_Message)
    ))
_sym_db.RegisterMessage(Distance_Coor_Single_Message)

Distance_Coor_Message = _reflection.GeneratedProtocolMessageType('Distance_Coor_Message', (_message.Message,), dict(
    DESCRIPTOR=_DISTANCE_COOR_MESSAGE,
    __module__='distance_protocol_pb2'
    # @@protoc_insertion_point(class_scope:Mioji.Distance.Distance_Coor_Message)
))
_sym_db.RegisterMessage(Distance_Coor_Message)

Distance_Info_Message = _reflection.GeneratedProtocolMessageType('Distance_Info_Message', (_message.Message,), dict(
    DESCRIPTOR=_DISTANCE_INFO_MESSAGE,
    __module__='distance_protocol_pb2'
    # @@protoc_insertion_point(class_scope:Mioji.Distance.Distance_Info_Message)
))
_sym_db.RegisterMessage(Distance_Info_Message)

Transfer_Message = _reflection.GeneratedProtocolMessageType('Transfer_Message', (_message.Message,), dict(
    DESCRIPTOR=_TRANSFER_MESSAGE,
    __module__='distance_protocol_pb2'
    # @@protoc_insertion_point(class_scope:Mioji.Distance.Transfer_Message)
))
_sym_db.RegisterMessage(Transfer_Message)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
