CREATE TABLE IF NOT EXISTS `%s` (
  `id` varchar(32) NOT NULL,
  `source` varchar(32) NOT NULL,
  `name` varchar(256) DEFAULT NULL,
  `name_en` varchar(256) DEFAULT NULL,
  `map_info` varchar(64) DEFAULT NULL,
  `city_id` varchar(64) NOT NULL,
  `source_city_id` varchar(16) DEFAULT NULL,
  `address` varchar(512) DEFAULT NULL,
  `ranking` varchar(512) DEFAULT NULL,
  `grade` varchar(11) DEFAULT NULL,
  `commentcounts` int(11) DEFAULT NULL,
  `cuisines` varchar(256) DEFAULT NULL,
  `dining_options` varchar(1024) DEFAULT NULL,
  `payment` varchar(256) DEFAULT NULL,
  `service` varchar(1024) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `michelin_star` float DEFAULT NULL,
  `recommend` varchar(64) DEFAULT NULL,
  `rating_by_category` varchar(32) DEFAULT NULL,
  `menu` text,
  `status` int(11) DEFAULT NULL,
  `flag` int(11) DEFAULT NULL,
  `url` varchar(320) NOT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `site` varchar(320) DEFAULT NULL,
  `imgurl` text,
  `commenturl` varchar(512) DEFAULT NULL,
  `introduction` text,
  `first_review_id` text,
  `opentime` varchar(1000) DEFAULT NULL,
  `price` varchar(1024) DEFAULT NULL,
  `price_level` varchar(32) DEFAULT NULL,
  `prize` int(11) DEFAULT NULL,
  `traveler_choice` int(11) DEFAULT NULL,
  `utime` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`,`source`,`city_id`),
    KEY `utime` (`utime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;