CREATE TABLE IF NOT EXISTS `%s` (
  `hotel_name` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `hotel_name_en` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `source` varchar(64) CHARACTER SET utf8 NOT NULL,
  `source_id` varchar(128) CHARACTER SET utf8 NOT NULL,
  `brand_name` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `map_info` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `address` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `city` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `country` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `city_id` varchar(11) CHARACTER SET utf8 NOT NULL,
  `postal_code` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `star` varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT -1,
  `grade` varchar(256) CHARACTER SET utf8 NOT NULL DEFAULT -1.0,
  `review_num` varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT -1,
  `has_wifi` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `is_wifi_free` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `has_parking` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `is_parking_free` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `service` text CHARACTER SET utf8,
  `img_items` text CHARACTER SET utf8,
  `description` text CHARACTER SET utf8,
  `accepted_cards` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `check_in_time` varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  `check_out_time` varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  `hotel_url` varchar(1024) CHARACTER SET utf8 DEFAULT NULL,
  `update_time` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `continent` varchar(96) CHARACTER SET utf8 DEFAULT NULL,
  `country_id` varchar(11) NOT NULL,
  PRIMARY KEY (`source`,`source_id`,`city_id`),
  KEY `update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;